apiVersion: v1
kind: Service
metadata:
  name: {{ .DNSSVCNAME }}
  namespace: kube-system
  annotations:
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "CoreDNS"
    addonmanager.kubernetes.io/mode: EnsureExists
spec:
  selector:
    k8s-app: kube-dns
    deploy: {{ .DNSDEPLOYNAME }}
  type: {{ .SVCTYPE }}
  ports:
    - name: dns
      port: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP
    - name: metrics
      port: 9153
      protocol: TCP
